export const QueryKey = {
  GET_ALL_POSTS: 'GET_ALL_POSTS',
  GET_POST_BY_ID: 'GET_POST_BY_ID',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_ALL_COMMENTS: 'GET_ALL_COMMENTS',
  GET_COMMENT_BY_ID: 'GET_COMMENT_BY_ID',
};
